vim.pack.add {
  {
    src = 'https://github.com/rose-pine/neovim',
    name = 'rose-pine',
  },
}

local paper_pine_dawn = {
  base = '#f7efe7',
  surface = '#f9f2eb',
  overlay = '#f2e8de',
  muted = '#9a92ab',
  subtle = '#7b7391',
  text = '#4e4945',
  love = '#c07a70',
  gold = '#c6a45d',
  rose = '#cb8d97',
  pine = '#5588b3',
  foam = '#7aa0c0',
  iris = '#8576b0',
  highlight_low = '#f2e8de',
  highlight_med = '#d8c2a7',
  highlight_high = '#ead9a7',
}

require('rose-pine').setup {
  variant = 'auto',

  styles = {
    bold = false,
    italic = false,
    transparency = false,
  },

  groups = {
    border = 'muted',
    link = 'iris',
    panel = 'surface',

    error = 'love',
    hint = 'iris',
    info = 'foam',
    note = 'pine',
    todo = 'rose',
    warn = 'gold',

    git_add = 'foam',
    git_change = 'rose',
    git_delete = 'love',
    git_dirty = 'rose',
    git_ignore = 'muted',
    git_merge = 'iris',
    git_rename = 'pine',
    git_stage = 'iris',
    git_text = 'rose',
    git_untracked = 'subtle',

    h1 = 'iris',
    h2 = 'foam',
    h3 = 'rose',
    h4 = 'gold',
    h5 = 'pine',
    h6 = 'foam',
  },

  palette = {
    dawn = paper_pine_dawn,
    main = {
      base = '#2a273f',
      surface = '#312d48',
      overlay = '#393552',
      muted = '#908caa',
      subtle = '#b2accf',
      text = '#f2ecff',
      love = '#eb6f92',
      gold = '#f6c177',
      rose = '#ebbcba',
      pine = '#3b7d95',
      foam = '#9ccfd8',
      iris = '#c4a7e7',
      highlight_low = '#322e4a',
      highlight_med = '#5c5878',
      highlight_high = '#7a7697',
    },
  },

  highlight_groups = {
    NormalFloat = { bg = 'surface' },
    FloatBorder = { fg = 'pine', bg = 'surface' },
    FloatTitle = { fg = 'pine', bg = 'surface' },
    CursorLine = { bg = 'overlay' },
    CursorColumn = { bg = 'overlay' },
    CursorLineNr = { fg = 'pine', bg = 'overlay' },
    LineNr = { fg = 'muted', bg = 'base' },
    SignColumn = { bg = 'base' },
    FoldColumn = { fg = 'muted', bg = 'base' },
    Folded = { fg = 'subtle', bg = 'overlay' },
    Visual = { fg = 'text', bg = 'highlight_med', inherit = false },
    VisualNOS = { fg = 'text', bg = 'highlight_med', inherit = false },
    Search = { fg = 'text', bg = 'highlight_high' },
    IncSearch = { fg = 'base', bg = 'pine' },
    MatchParen = { fg = 'rose', bg = 'highlight_med' },

    StatusLine = { fg = 'text', bg = 'overlay' },
    StatusLineNC = { fg = 'muted', bg = 'overlay' },
    TabLine = { fg = 'subtle', bg = 'overlay' },
    TabLineFill = { bg = 'overlay' },
    TabLineSel = { fg = 'text', bg = 'base' },

    Pmenu = { fg = 'text', bg = 'surface' },
    PmenuBorder = { fg = 'pine', bg = 'surface' },
    PmenuSel = { fg = 'text', bg = 'highlight_med' },
    PmenuSbar = { bg = 'overlay' },
    PmenuThumb = { bg = 'highlight_med' },

    Comment = { fg = 'subtle', italic = true },
    Constant = { fg = 'gold' },
    String = { fg = '#e39a2d' },
    Character = { fg = '#e39a2d' },
    Number = { fg = 'gold' },
    Boolean = { fg = 'gold' },
    Float = { fg = 'gold' },
    Identifier = { fg = 'text' },
    Function = { fg = 'rose' },
    Statement = { fg = 'pine' },
    Conditional = { fg = 'pine' },
    Repeat = { fg = 'pine' },
    Label = { fg = 'pine' },
    Operator = { fg = 'text' },
    Keyword = { fg = 'pine' },
    Exception = { fg = 'pine' },
    PreProc = { fg = 'iris' },
    Include = { fg = 'pine' },
    Define = { fg = 'iris' },
    Macro = { fg = 'iris' },
    PreCondit = { fg = 'iris' },
    Type = { fg = 'pine' },
    StorageClass = { fg = 'pine' },
    Structure = { fg = 'pine' },
    Typedef = { fg = 'pine' },
    Special = { fg = 'rose' },
    SpecialChar = { fg = 'rose' },
    Delimiter = { fg = 'subtle' },
    SpecialComment = { fg = 'muted', italic = true },

    ['@variable'] = { fg = 'text' },
    ['@variable.builtin'] = { fg = 'foam' },
    ['@parameter'] = { fg = 'text' },
    ['@field'] = { fg = 'rose' },
    ['@property'] = { fg = 'rose' },
    ['@function'] = { fg = 'rose' },
    ['@function.call'] = { fg = 'rose' },
    ['@function.builtin'] = { fg = 'iris' },
    ['@method'] = { fg = 'rose' },
    ['@method.call'] = { fg = 'rose' },
    ['@constructor'] = { fg = 'pine' },
    ['@keyword'] = { fg = 'pine' },
    ['@keyword.function'] = { fg = 'pine' },
    ['@keyword.operator'] = { fg = 'pine' },
    ['@keyword.return'] = { fg = 'pine' },
    ['@operator'] = { fg = 'text' },
    ['@type'] = { fg = 'pine' },
    ['@type.builtin'] = { fg = 'pine' },
    ['@module'] = { fg = 'pine' },
    ['@attribute'] = { fg = 'iris' },
    ['@lsp.type.annotation'] = { fg = 'iris' },
    ['@lsp.type.comment'] = { fg = 'muted', italic = true },
    ['@constant'] = { fg = 'gold' },
    ['@string'] = { fg = '#e39a2d' },
    ['@string.escape'] = { fg = 'rose' },
    ['@number'] = { fg = 'gold' },
    ['@boolean'] = { fg = 'gold' },
    ['@comment'] = { fg = 'muted', italic = true },

    DiagnosticError = { fg = 'love' },
    DiagnosticWarn = { fg = 'gold' },
    DiagnosticInfo = { fg = 'foam' },
    DiagnosticHint = { fg = 'foam' },

    FzfLuaNormal = { link = 'NormalFloat' },
    FzfLuaBorder = { link = 'FloatBorder' },
    FzfLuaTitle = { link = 'FloatTitle' },
    FzfLuaPreviewNormal = { link = 'NormalFloat' },
    FzfLuaPreviewBorder = { link = 'FloatBorder' },
    FzfLuaPreviewTitle = { link = 'FloatTitle' },
    FzfLuaCursorLine = { bg = 'highlight_med' },
    FzfLuaCursorLineNr = { fg = 'pine', bg = 'highlight_med' },
    FzfLuaFzfNormal = { fg = 'text', bg = 'surface' },
    FzfLuaFzfCursorLine = { fg = 'text', bg = 'highlight_med' },
    FzfLuaFzfMatch = { fg = 'pine' },
    FzfLuaFilePart = { fg = 'text' },
    FzfLuaDirPart = { fg = 'subtle' },
    FzfLuaPathLineNr = { fg = 'pine' },
    FzfLuaPathColNr = { fg = 'pine' },

    BlinkCmpMenu = { link = 'Pmenu' },
    BlinkCmpMenuBorder = { link = 'PmenuBorder' },
    BlinkCmpMenuSelection = { link = 'PmenuSel' },
    BlinkCmpDoc = { link = 'NormalFloat' },
    BlinkCmpDocBorder = { link = 'FloatBorder' },
    BlinkCmpDocSeparator = { link = 'FloatBorder' },
    BlinkCmpSignatureHelp = { link = 'NormalFloat' },
    BlinkCmpSignatureHelpBorder = { link = 'FloatBorder' },
    BlinkCmpScrollBarThumb = { link = 'PmenuThumb' },
    BlinkCmpScrollBarGutter = { link = 'PmenuSbar' },
  },
}

vim.cmd.colorscheme 'rose-pine'
