set -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm-256color:Tc,*:Ss=\E[%p1%d q:Se=\E[ q' # fix for non blinking cursor in tmux sessions 

unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

set -g base-index 1  

set -g status-style 'bg=default fg=#5eacd3'
set -g status-left ''
set -g status-right ''
set -g status-justify left
set -g status-position bottom

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# clears term screen
bind r send-keys -R \; clear-history \; send-keys C-l

# set vi-mode
set-window-option -g mode-keys vi

# creates new tmux window from current dir
bind -r n new-window -c "#{pane_current_path}"

# kill session
bind-key K kill-session

# deletes current window
bind q kill-pane

# switch between tmux windows with Ctrl+[ and Ctrl+]
bind -n C-] next-window
bind -n C-[ previous-window

set-option -g default-shell /opt/homebrew/bin/fish

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
